name: chat165_anti_scam
description: Chat165 防詐騙應用 - 國家反詐中心風格

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  
  speech_to_text: ^7.0.0
  voice_message_package: ^2.2.1  # 語音訊息UI元件
  double_back_to_close: ^2.0.0  # 用於iOS雙擊檢測
  sensors_plus: ^6.1.1
  permission_handler: ^11.0.1
  vibration: ^3.1.3            # 震動反饋


flutter:
  uses-material-design: true
  assets:
    - assets/images/